fix(debos/rootfs): fix locale-gen invocation
Call locale-gen without arguments so it reads /etc/locale.gen. This
improves compatibility of the recipes with Ubuntu, even if Ubuntu is
unsupported right now.

Previously the extra "UTF-8" argument was interpreted by Ubuntu's
locale-gen as a second (invalid) locale name:
    Error: 'UTF-8' is not a supported language or locale

Signed-off-by: Loïc Minier <loic.minier@oss.qualcomm.com>